services:
  postgres:
    image: postgres:latest
    container_name: guestbook_postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: guestbook
      POSTGRES_PASSWORD: guestbook
      POSTGRES_DB: guestbook
    volumes:
      - ../.docker/postgres:/var/lib/postgresql/data